In [23]:
import numpy as np
import trax

In [24]:
from trax import layers as tl
from trax import shapes, fastmath

In [25]:
from trax.fastmath import numpy as fastnp

In [26]:
one = fastnp.ones([4,4])

In [27]:
one

DeviceArray([[1., 1., 1., 1.],
             [1., 1., 1., 1.],
             [1., 1., 1., 1.],
             [1., 1., 1., 1.]], dtype=float32)

In [28]:
one + 1

DeviceArray([[2., 2., 2., 2.],
             [2., 2., 2., 2.],
             [2., 2., 2., 2.],
             [2., 2., 2., 2.]], dtype=float32)

In [29]:
x = fastnp.array([[1, 1, 1, 1],[1, 1, 1, 1]])

In [30]:
fastnp.dot(x, one)

DeviceArray([[4., 4., 4., 4.],
             [4., 4., 4., 4.]], dtype=float32)

In [31]:
def f(x):
    return 2 * x * x
    

In [32]:
grad_f = trax.fastmath.grad(f)

In [33]:
trax

<module 'trax' from '/home/prhyme/.local/lib/python3.8/site-packages/trax/__init__.py'>

In [35]:
grad_f(1.0)

DeviceArray(4., dtype=float32)

In [37]:
print(grad_f(2.0))

8.0
